steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/web/Dockerfile
      - --build-arg
      - NEXT_PUBLIC_API_URL=https://venueflow-api-733457865640.asia-south1.run.app
      - --build-arg
      - NEXT_PUBLIC_SOCKET_URL=https://venueflow-api-733457865640.asia-south1.run.app
      - --build-arg
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AIzaSyBiA-pbd3X7IG80Q-8wbLwZZ9D4lTnck_Q
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_API_KEY=demo-api-key-for-emulator
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=event-project-493505.firebaseapp.com
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=event-project-493505
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=event-project-493505.firebasestorage.app
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=000000000000
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_APP_ID=1:000000000000:web:placeholder
      - --build-arg
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=
      - --build-arg
      - NEXT_PUBLIC_APP_URL=https://venueflow-web-733457865640.asia-south1.run.app
      - --build-arg
      - NEXT_PUBLIC_USE_EMULATOR=false
      - -t
      - asia-south1-docker.pkg.dev/event-project-493505/venueflow/venueflow-web:latest
      - .
images:
  - asia-south1-docker.pkg.dev/event-project-493505/venueflow/venueflow-web:latest
